config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "profile", to: "pages#profile"
  resources :cars, only: [:index, :show] do
    resources :bookings, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :car


  validates :start_date, :end_date, presence: true
  validate :end_date_after_start_date

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
  end

end

app/models/car.rb
class Car < ApplicationRecord
  has_many :bookings
  belongs_to :user
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?


  def unavailable_dates
    bookings.pluck(:start_date, :end_date).map do |range|
      { from: range[0], to: range[1] }
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings, dependent: :destroy
  has_many :cars, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_car, only: %i[create]



  def create
    @booking = Booking.new(booking_params)
    @booking.car = @car
    @booking.user = current_user
    @booking.total_price = (Date.parse(@booking.end_date) - Date.parse(@booking.start_date)).to_i * @car.price_per_day
    if @booking.save!
      redirect_to profile_path
    else
      render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to profile_path, status: :see_other
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :user_id, :car_id)
  end

  def set_car
    @car = Car.find(params[:car_id])
  end




end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show]
  before_action :set_car, only: [:show]
  before_action :set_user


  def index
    if params[:query].present?
      sql_query = "cars.title @@ :query \
      OR cars.address @@ :query \
      OR cars.car_type @@ :query"
      @cars = Car.where(sql_query, query: "%#{params[:query]}%")
    else
      @cars = Car.all
    end
    @markers = @cars.geocoded.map do |car|
      {
        lat: car.latitude + rand(0..1),
        lng: car.longitude + rand(0..1),
        info_window: render_to_string(partial: "info_window", locals: {car: car})
      }
    end
  end

  def show
    @booking = Booking.new
    @marker_car = Car.where(id: @car.id)
    @markers = @marker_car.geocoded.map do |car|
      {
        lat: car.latitude,
        lng: car.longitude,
        info_window: render_to_string(partial: "info_window", locals: {car: car})
      }
    end
  end


  private

  def set_car
    @car = Car.find(params[:id])
  end

  def set_user
    @user = current_user if user_signed_in?
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]
  before_action :set_user


  def home
    @cars = Car.all
  end

  def profile
    @user = current_user
  end

private

  def set_user
    @user = current_user if user_signed_in?
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/_info_window.html.erb
<%= link_to(car_path(car.id), class: "map-info-box") do %>
  <p><%= car.title %> - <%= car.address %></p>
  <%=  cl_image_tag car.photo.key, width: 200, height: 100, crop: :fill %>
<% end %>

app/views/cars/index.html.erb
<div class="container">
  <%= form_with url: cars_path, method: :get, class: "d-flex my-4" do %>
    <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find a car by state, make or model"
  %>
    <%= submit_tag "Find", class: "btn btn-primary" %>
  <% end %>
<div class="row">
  <div class="col-12 col-lg-4">
    <div class="cards-index">
      <% @cars.each do |car| %>
        <%= link_to(car_path(car.id)) do %>
                  <div class="card-place m-2 my-4">
          <%=  cl_image_tag car.photo.key %>
          <div class="card-place-infos p-3">
            <div>
              <h2 class="mb-2"><%= car.title %></h2>
              <p><%= "#{car.car_type} - #{car.fuel_type} - #{car.transmission}" %></p>
              <p><%= car.address %></p>
            </div>
            <h2 class="card-place-pricing"><%= "$#{car.price_per_day}/day" %></h2>
        </div>
      </div>

        <% end %>
      <% end %>

    </div>
  </div>

  <div class="col-12 col-lg-8 my-4">
<div style="width: 100%; height: 500px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
</div>

</div>
</div>

app/views/cars/show.html.erb
<div class="container my-5">
   <div class="row">
      <div class="col-12 col-lg-7">
         <%= cl_image_tag @car.photo.key, crop: :fill, class: "d-block w-100"%>
         <p id="booking-infos" class="mt-5 ms-5"></p>
      </div>
      <div class="col-12 col-lg-5 d-flex flex-column">
         <h2 class="mb-4 text-center"><strong><%= @car.title %></strong></h2>
         <p><strong>Localization</strong> : <%= @car.street_address %>, <%= @car.address %></p>
         <p><strong>Car type</strong> : <%= @car.car_type %></p>
         <p><strong>Mileage</strong> : <%= @car.mileage %>km</p>
         <p><strong>Fuel type</strong> : <%= @car.fuel_type %></p>
         <p><strong>Transmission</strong> : <%= @car.transmission %></p>
         <p><strong>Year</strong> : <%= @car.year %></p>
         <p><strong>Price per day</strong> : $<span id="price_per_day"><%= @car.price_per_day %></span></p>
         <% if user_signed_in? %>
         <h2 class="m-3 text-center">Book this car</h2>
         <div class="form-wrapper" style="width: 400px; margin: 0 auto;">
            <div id='car-booking-dates' data-unavailable="<%= @car.unavailable_dates.to_json %>">
               <%= simple_form_for [@car, @booking], data: { turbo: false }  do |f| %>
               <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
               <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
               <%= f.button :submit, "Go", class: "btn btn-primary", id: "submit-button" %>
               <% end %>
            </div>
         </div>
         <% else %>
         <h2><%= link_to "Sign in to book this car", new_user_session_path, class: "nav-link" %></h2>
         <% end %>
      </div>
   </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kingparking</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('favicon.png') %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></script>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://i.imgur.com/3Mr6U2q.png);">
  <div class="container">
    <h1>Rent a car with KINGPARKING !</h1>
    <p>Find a rental car near you, anywhere in the US</p>
    <%= link_to "Find a car", cars_path, class: "btn btn-primary" %>
  </div>
</div>

<div class="container my-5">
  <div class="row">
  <h3 class="text-center my-2" id="home-title">Latest cars</h3>
      <% @cars.sample(12).each do |car| %>
      <div class="p-4 col-12 col-lg-4">
      <div class="cards-home">
      <%= link_to(car_path(car.id)) do %>
        <div class="card-place m-2">
          <%=  cl_image_tag car.photo.key %>
          <div class="card-place-infos p-3">
            <div>
              <h2 class="mb-2"><%= car.title %></h2>
              <p><%= "#{car.car_type} - #{car.fuel_type} - #{car.transmission}" %></p>
              <p><%= car.address %></p>
            </div>
            <h2 class="card-place-pricing"><%= "$#{car.price_per_day}/day" %></h2>
        </div>
      </div>
      </div>
      <% end %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/profile.html.erb
<div class="container">
   <h2 class="mt-3 text-center">Welcome <%= @user.first_name%> ! Manage your bookings:</h2>
    <div class="row justify-content-center">
    <div class="col-12 col-lg-6">
   <% @user.bookings.reverse.each do |booking| %>
   <div class="card-product my-3">
      <%=  cl_image_tag booking.car.photo.key %>
      <div class="card-product-infos">
      <%= link_to(car_path(booking.car.id), data: { turbo: false }) do %>
         <h2>Booking for <%= booking.car.title %> in <%= booking.car.address %></h2>
         <% end %>
         <p>From <strong><%= booking.start_date %></strong> to <strong><%= booking.end_date %></strong> - Total price : <strong>$<%= booking.total_price %></strong></p>
         <p><%= mail_to booking.car.user.email, "Contact owner" %></p>
         <%= link_to(car_booking_path(booking.car.id, booking.id), data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to cancel this booking ?"}) do%>
         <i class="fa-solid fa-trash-can"></i>
         <% end %>
      </div>
   </div>
   <% end %>
   </div>
   </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    ©2022 KINGPARKING
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "favicon.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
          <%= link_to "#{@user.first_name} #{@user.last_name}'s bookings", profile_path	, class: "nav-link fw-bold" %>
          </li>
          <li class="nav-item">
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>